name = "kwalis-website"
main = "worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "kwalis.ai", zone_name = "kwalis.ai", custom_domain = true }
]

[assets]
directory = "dist"

[[d1_databases]]
binding = "DB"
database_name = "kwalis-signups"
database_id = "464e9790-b9ef-460d-a480-235d9484fa07"
